name: flutter_timer
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  bloc: ^7.0.0
  equatable: ^2.0.0
  wave: ^0.2.0
  flutter_bloc: ^7.0.0

#dependency_overrides:
#  bloc:
#    path: ../../packages/bloc
#  flutter_bloc:
#    path: ../../packages/flutter_bloc
#  bloc_test:
#    path: ../../packages/bloc_test

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.2
  integration_test: ^1.0.2+3

flutter:
  uses-material-design: true
